# Site Config

name: xelA
title: xelA

themecolour: "#2196F3"

domain: "https://docs.xela.dev"
baseurl: ""
url: "https://docs.xela.dev"
encoding: utf-8

include: ['_pages']

sass:
  sass_dir: _sass
  style: compressed
